spring.application.name=backend

#  SERVER
server.port=8080


#  DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/villa_elbling
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver


#  JPA / HIBERNATE
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


#  APPLICATION
app.name=Villa Elbling Booking System
app.booking-reference-prefix=VE
app.session-expiry-hours=8
app.cors-allowed-origins=http://localhost:3000


#  LOGGING
logging.level.com.villaelbling=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
